
export const moviesData = [
  {
    country: 'Россия',
    director: 'Наталья Климчук',
    duration: 100,
    year: 2019,
    description: 'Фильм-исследование дизайна в России. ',
    image: 'images/aboutDesign.png',
    trailerLink: 'https://ya.ru/',
    thumbnail: 'https://ya.ru/',
    movieId: 1,
    nameRU: '33 слова о дизайне',
    nameEN: '33 WORDS ABOUT DESIGN',
  },
  {
    country: 'Россия',
    director: 'Наталья Климчук',
    duration: 100,
    year: 2019,
    description: 'Фильм-исследование дизайна в России. ',
    image: 'images/aboutDesign.png',
    trailerLink: 'https://ya.ru/',
    thumbnail: 'https://ya.ru/',
    movieId: 2,
    nameRU: '33 слова о дизайне',
    nameEN: '33 WORDS ABOUT DESIGN',
  },
  {
    country: 'Россия',
    director: 'Наталья Климчук',
    duration: 100,
    year: 2019,
    description: 'Фильм-исследование дизайна в России. ',
    image: 'images/aboutDesign.png',
    trailerLink: 'https://ya.ru/',
    thumbnail: 'https://ya.ru/',
    movieId: 3,
    nameRU: '33 слова о дизайне',
    nameEN: '33 WORDS ABOUT DESIGN',
  },
  {
    country: 'Россия',
    director: 'Наталья Климчук',
    duration: 100,
    year: 2019,
    description: 'Фильм-исследование дизайна в России. ',
    image: 'images/aboutDesign.png',
    trailerLink: 'https://ya.ru/',
    thumbnail: 'https://ya.ru/',
    movieId: 4,
    nameRU: '33 слова о дизайне',
    nameEN: '33 WORDS ABOUT DESIGN',
  },
  {
    country: 'Россия',
    director: 'Наталья Климчук',
    duration: 100,
    year: 2019,
    description: 'Фильм-исследование дизайна в России. ',
    image: 'images/aboutDesign.png',
    trailerLink: 'https://ya.ru/',
    thumbnail: 'https://ya.ru/',
    movieId: 5,
    nameRU: '33 слова о дизайне',
    nameEN: '33 WORDS ABOUT DESIGN',
  },
  {
    country: 'Россия',
    director: 'Наталья Климчук',
    duration: 100,
    year: 2019,
    description: 'Фильм-исследование дизайна в России. ',
    image: 'images/aboutDesign.png',
    trailerLink: 'https://ya.ru/',
    thumbnail: 'https://ya.ru/',
    movieId: 6,
    nameRU: '33 слова о дизайне',
    nameEN: '33 WORDS ABOUT DESIGN',
  },
  {
    country: 'Россия',
    director: 'Наталья Климчук',
    duration: 100,
    year: 2019,
    description: 'Фильм-исследование дизайна в России. ',
    image: 'images/aboutDesign.png',
    trailerLink: 'https://ya.ru/',
    thumbnail: 'https://ya.ru/',
    movieId: 7,
    nameRU: '33 слова о дизайне',
    nameEN: '33 WORDS ABOUT DESIGN',
  },
  {
    country: 'Россия',
    director: 'Наталья Климчук',
    duration: 100,
    year: 2019,
    description: 'Фильм-исследование дизайна в России. ',
    image: 'images/aboutDesign.png',
    trailerLink: 'https://ya.ru/',
    thumbnail: 'https://ya.ru/',
    movieId: 8,
    nameRU: '33 слова о дизайне',
    nameEN: '33 WORDS ABOUT DESIGN',
  },
  {
    country: 'Россия',
    director: 'Наталья Климчук',
    duration: 100,
    year: 2019,
    description: 'Фильм-исследование дизайна в России. ',
    image: 'images/aboutDesign.png',
    trailerLink: 'https://ya.ru/',
    thumbnail: 'https://ya.ru/',
    movieId: 9,
    nameRU: '33 слова о дизайне',
    nameEN: '33 WORDS ABOUT DESIGN',
  },
  {
    country: 'Россия',
    director: 'Наталья Климчук',
    duration: 100,
    year: 2019,
    description: 'Фильм-исследование дизайна в России. ',
    image: 'images/aboutDesign.png',
    trailerLink: 'https://ya.ru/',
    thumbnail: 'https://ya.ru/',
    movieId: 10,
    nameRU: '33 слова о дизайне',
    nameEN: '33 WORDS ABOUT DESIGN',
  },
  {
    country: 'Россия',
    director: 'Наталья Климчук',
    duration: 100,
    year: 2019,
    description: 'Фильм-исследование дизайна в России. ',
    image: 'images/aboutDesign.png',
    trailerLink: 'https://ya.ru/',
    thumbnail: 'https://ya.ru/',
    movieId: 11,
    nameRU: '33 слова о дизайне',
    nameEN: '33 WORDS ABOUT DESIGN',
  },
  {
    country: 'Россия',
    director: 'Наталья Климчук',
    duration: 100,
    year: 2019,
    description: 'Фильм-исследование дизайна в России. ',
    image: 'images/aboutDesign.png',
    trailerLink: 'https://ya.ru/',
    thumbnail: 'https://ya.ru/',
    movieId: 12,
    nameRU: '33 слова о дизайне',
    nameEN: '33 WORDS ABOUT DESIGN',
  },

]

export const saveMoviesData = [
  {
    country: 'Россия',
    director: 'Наталья Климчук',
    duration: 100,
    year: 2019,
    description: 'Фильм-исследование дизайна в России. ',
    image: 'images/aboutDesign.png',
    trailerLink: 'https://ya.ru/',
    thumbnail: 'https://ya.ru/',
    movieId: 111,
    nameRU: '33 слова о дизайне',
    nameEN: '33 WORDS ABOUT DESIGN',
  },
  {
    country: 'Россия',
    director: 'Наталья Климчук',
    duration: 100,
    year: 2019,
    description: 'Фильм-исследование дизайна в России. ',
    image: 'images/aboutDesign.png',
    trailerLink: 'https://ya.ru/',
    thumbnail: 'https://ya.ru/',
    movieId: 112,
    nameRU: '33 слова о дизайне',
    nameEN: '33 WORDS ABOUT DESIGN',
  },
  {
    country: 'Россия',
    director: 'Наталья Климчук',
    duration: 100,
    year: 2019,
    description: 'Фильм-исследование дизайна в России. ',
    image: 'images/aboutDesign.png',
    trailerLink: 'https://ya.ru/',
    thumbnail: 'https://ya.ru/',
    movieId: 113,
    nameRU: '33 слова о дизайне',
    nameEN: '33 WORDS ABOUT DESIGN',
  },
  {
    country: 'Россия',
    director: 'Наталья Климчук',
    duration: 100,
    year: 2019,
    description: 'Фильм-исследование дизайна в России. ',
    image: 'images/aboutDesign.png',
    trailerLink: 'https://ya.ru/',
    thumbnail: 'https://ya.ru/',
    movieId: 114,
    nameRU: '33 слова о дизайне',
    nameEN: '33 WORDS ABOUT DESIGN',
  },

]
