
const moviesData = [
  {
    country: 'Россия',
    director: 'Наталья Климчук',
    duration: 100,
    year: 2019,
    description: 'Фильм-исследование дизайна в России. ',
    image: 'images/aboutDesign.png',
    trailerLink: 'https://ya.ru/',
    thumbnail: 'https://ya.ru/',
    movieId: 1,
    nameRU: '33 слова о дизайне',
    nameEN: "33 WORDS ABOUT DESIGN",
  },
  {
    country: 'Россия',
    director: 'Наталья Климчук',
    duration: 100,
    year: 2019,
    description: 'Фильм-исследование дизайна в России. ',
    image: 'images/aboutDesign.png',
    trailerLink: 'https://ya.ru/',
    thumbnail: 'https://ya.ru/',
    movieId: 2,
    nameRU: '33 слова о дизайне',
    nameEN: "33 WORDS ABOUT DESIGN",
  },
  {
    country: 'Россия',
    director: 'Наталья Климчук',
    duration: 100,
    year: 2019,
    description: 'Фильм-исследование дизайна в России. ',
    image: 'images/aboutDesign.png',
    trailerLink: 'https://ya.ru/',
    thumbnail: 'https://ya.ru/',
    movieId: 3,
    nameRU: '33 слова о дизайне',
    nameEN: "33 WORDS ABOUT DESIGN",
  },
  {
    country: 'Россия',
    director: 'Наталья Климчук',
    duration: 100,
    year: 2019,
    description: 'Фильм-исследование дизайна в России. ',
    image: 'images/aboutDesign.png',
    trailerLink: 'https://ya.ru/',
    thumbnail: 'https://ya.ru/',
    movieId: 4,
    nameRU: '33 слова о дизайне',
    nameEN: "33 WORDS ABOUT DESIGN",
  },
  {
    country: 'Россия',
    director: 'Наталья Климчук',
    duration: 100,
    year: 2019,
    description: 'Фильм-исследование дизайна в России. ',
    image: 'images/aboutDesign.png',
    trailerLink: 'https://ya.ru/',
    thumbnail: 'https://ya.ru/',
    movieId: 5,
    nameRU: '33 слова о дизайне',
    nameEN: "33 WORDS ABOUT DESIGN",
  },
  {
    country: 'Россия',
    director: 'Наталья Климчук',
    duration: 100,
    year: 2019,
    description: 'Фильм-исследование дизайна в России. ',
    image: 'images/aboutDesign.png',
    trailerLink: 'https://ya.ru/',
    thumbnail: 'https://ya.ru/',
    movieId: 6,
    nameRU: '33 слова о дизайне',
    nameEN: "33 WORDS ABOUT DESIGN",
  },
  {
    country: 'Россия',
    director: 'Наталья Климчук',
    duration: 100,
    year: 2019,
    description: 'Фильм-исследование дизайна в России. ',
    image: 'images/aboutDesign.png',
    trailerLink: 'https://ya.ru/',
    thumbnail: 'https://ya.ru/',
    movieId: 1,
    nameRU: '33 слова о дизайне',
    nameEN: "33 WORDS ABOUT DESIGN",
  },
  {
    country: 'Россия',
    director: 'Наталья Климчук',
    duration: 100,
    year: 2019,
    description: 'Фильм-исследование дизайна в России. ',
    image: 'images/aboutDesign.png',
    trailerLink: 'https://ya.ru/',
    thumbnail: 'https://ya.ru/',
    movieId: 2,
    nameRU: '33 слова о дизайне',
    nameEN: "33 WORDS ABOUT DESIGN",
  },
  {
    country: 'Россия',
    director: 'Наталья Климчук',
    duration: 100,
    year: 2019,
    description: 'Фильм-исследование дизайна в России. ',
    image: 'images/aboutDesign.png',
    trailerLink: 'https://ya.ru/',
    thumbnail: 'https://ya.ru/',
    movieId: 3,
    nameRU: '33 слова о дизайне',
    nameEN: "33 WORDS ABOUT DESIGN",
  },
  {
    country: 'Россия',
    director: 'Наталья Климчук',
    duration: 100,
    year: 2019,
    description: 'Фильм-исследование дизайна в России. ',
    image: 'images/aboutDesign.png',
    trailerLink: 'https://ya.ru/',
    thumbnail: 'https://ya.ru/',
    movieId: 4,
    nameRU: '33 слова о дизайне',
    nameEN: "33 WORDS ABOUT DESIGN",
  },
  {
    country: 'Россия',
    director: 'Наталья Климчук',
    duration: 100,
    year: 2019,
    description: 'Фильм-исследование дизайна в России. ',
    image: 'images/aboutDesign.png',
    trailerLink: 'https://ya.ru/',
    thumbnail: 'https://ya.ru/',
    movieId: 5,
    nameRU: '33 слова о дизайне',
    nameEN: "33 WORDS ABOUT DESIGN",
  },
  {
    country: 'Россия',
    director: 'Наталья Климчук',
    duration: 100,
    year: 2019,
    description: 'Фильм-исследование дизайна в России. ',
    image: 'images/aboutDesign.png',
    trailerLink: 'https://ya.ru/',
    thumbnail: 'https://ya.ru/',
    movieId: 6,
    nameRU: '33 слова о дизайне',
    nameEN: "33 WORDS ABOUT DESIGN",
  },
  {
    country: 'Россия',
    director: 'Наталья Климчук',
    duration: 100,
    year: 2019,
    description: 'Фильм-исследование дизайна в России. ',
    image: 'images/aboutDesign.png',
    trailerLink: 'https://ya.ru/',
    thumbnail: 'https://ya.ru/',
    movieId: 2,
    nameRU: '33 слова о дизайне',
    nameEN: "33 WORDS ABOUT DESIGN",
  },
  {
    country: 'Россия',
    director: 'Наталья Климчук',
    duration: 100,
    year: 2019,
    description: 'Фильм-исследование дизайна в России. ',
    image: 'images/aboutDesign.png',
    trailerLink: 'https://ya.ru/',
    thumbnail: 'https://ya.ru/',
    movieId: 3,
    nameRU: '33 слова о дизайне',
    nameEN: "33 WORDS ABOUT DESIGN",
  },
  {
    country: 'Россия',
    director: 'Наталья Климчук',
    duration: 100,
    year: 2019,
    description: 'Фильм-исследование дизайна в России. ',
    image: 'images/aboutDesign.png',
    trailerLink: 'https://ya.ru/',
    thumbnail: 'https://ya.ru/',
    movieId: 4,
    nameRU: '33 слова о дизайне',
    nameEN: "33 WORDS ABOUT DESIGN",
  },
  {
    country: 'Россия',
    director: 'Наталья Климчук',
    duration: 100,
    year: 2019,
    description: 'Фильм-исследование дизайна в России. ',
    image: 'images/aboutDesign.png',
    trailerLink: 'https://ya.ru/',
    thumbnail: 'https://ya.ru/',
    movieId: 5,
    nameRU: '33 слова о дизайне',
    nameEN: "33 WORDS ABOUT DESIGN",
  },

]

export default moviesData
